name: Publish Docker image

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  push_to_registry:
    name: build and publish Docker image
    runs-on: ubuntu-latest
    env:
      GITHUB_USER: ${{ github.repository_owner }}
      IMAGE_NAME: ${{ github.repository }}
      IMAGE_VERSION: v1.0
    steps:
    - uses: actions/checkout@v3
    - name: Build Docker Image
      run: |
        docker build . -t $IMAGE_NAME:$IMAGE_VERSION -t ghcr.io/$IMAGE_NAME:$IMAGE_VERSION
    - name: Publish to GitHub Container registry
      run: |
        docker login ghcr.io -u $GITHUB_USER -p ${{ secrets.GITHUB_TOKEN }}
        docker push ghcr.io/$IMAGE_NAME:$IMAGE_VERSION