name: Publish Docker image

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  push_to_registry:
    name: push Docker image to GitHub Container Registry
    runs-on: ubuntu-latest
    env:
      GITHUB_USER: $GITHUB_REPOSITORY_OWNER
      IMAGE_NAME: $GITHUB_REPOSITORY
      IMAGE_VERSION: v1.0
    steps:
    - name: Build Docker Image

    - name: Publish to GitHub Container registry
      run: |
        docker login ghcr.io -u $GITHUB_USER -p ${{ secrets.GITHUB_TOKEN }}
        docker push ghcr.io/$IMAGE_NAME:$IMAGE_VERSION

