name: deployment

on:
  workflow_dispatch:
  push:

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: prepare data
      run: zip -r data.zip data
    - name: Branch name
      run: echo running on branch ${GITHUB_REF##*/}
    - name: create release
      uses: softprops/action-gh-release@v1
      with:
        files: data.zip