name: deployment

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: prepare data
      run: zip -r data.zip data
    - name: upload data
      uses: actions/upload-artifact@v3
      with:
        name: data
        path: data.zip
    - name: create release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: data.zip